import Head from "next/head";
import Link from "next/link";
//import {homeStyles} from "styles/home";
import Image from "next/image";


export default function Home() {
  return (
    <div className="sm:container lg:container lg:mx-auto container text h-screen flex flex-col items-center border border-black pt-10 px-5 ">
      <Head>
        <title> Terpel </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image className="rounded-full" src="/Sonriendo.svg" width={200} height={200} />

      <p className="text-red-600 mt-6 mr-5 ml-5 font-extrabold text-2xl text-orangePrimary w-80 h-8 text-center ">Nos alegra saludarte</p>
      <p className="mt-2 text-center text-lg text-neutral">Bienviendo a Vive Terpel, aquí inicia tu viaje de grandes beneficios</p>

      <button disabled={true} className="bg-orangePrimary text-white px-8 py-4 w-80 rounded-xl mt-10 text-lg">
        Iniciar sesión
      </button>

      <p className="mt-7 text-lg text-neutral pb">
        ¿No tienes una cuenta? <span className="text-neutral font-bold">  <Link href="#">Regístrate </Link> </span> 
      </p>

      <div className="mt-16 text-sm text-neutral flex items-center">
       <p className="pr-1"> Ingresar sin  <span className="font-bold">registrarme</span> </p> 
        <Image src="/flechaAdelante.svg" width={18} height={18} />
      </div>
    </div>
  );
}
